### ISSUE TITLE
Redirect old tidy web site URL

### ISSUE THREAD

**Issue by ryandesign** [htacg/htacg.github.io#2]
The tidy web site used to be accessible at http://www.htacg.org/tidy-html5/; now that's 404 not found. Please add a redirect to the new web site http://www.html-tidy.org. It looks like 106632f0288e03603cf704add5e28660e5966436 tried to do this but it was undone in 43946291ed640437404b2067625a64b59515d82c. I don't care how you do it, but it is imperative for the proper functioning of the web that old URLs do not go 404.

**Comment by balthisar** [comment]
Yeah, the fact that it used to be available that way is a characteristic of how Github pages work. It was _never_ meant to work as a subdirectory and we would have prevented that if we had known it would operate that way at the time.

Also because of the way gh-pages work, if I attempt to add a redirect then it will simply cause an endless loop.

I'll take a look at it again tonight. Now that we moved the site into a separate repo, then _maybe_ there's something I can do about it, but I'm not sure. Github doesn't give me .htaccess access.

**Comment by balthisar** [comment]
@ryandesign, thanks for the report. Moving the gh-pages into its own repot and faking the 301 did the trick. You should see correct behavior now for those level links.

However _do_ keep in mind that because we don't have `.htaccess`, deeper links _will_ continue to 404. I could recursively redirect all of them manually, but I don't think I will unless someone shows me a link from, e.g., the New York Times or Slashdot that links deeper.

**Comment by ryandesign** [comment]
Thanks. I would have thought a jekyll `redirect_to` should have worked...

https://github.com/jekyll/jekyll-redirect-from
